version: '2'
services:
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fridgeater
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - web
      - vue
  vue:
    build:
      context: frontend
      dockerfile: Dockerfile