spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/fridgeater?createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test
    password: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
server:
  servlet:
    context-path: /fridgeater/rest
  port: 8090
logging:
  file: log/application.log

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://db:3306/fridgeater?createDatabaseIfNotExist=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
server:
  servlet:
    context-path: /fridgeater/rest
  port: 8090
logging:
  file: log/application.log